version: 2.1  # Adjust if needed based on CircleCI version
jobs:
  run-LTAF:
    docker:
      - image: cypress/included:13.15.2
    parallelism: 3
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run --parallel --record --key 16c12140-46c2-4e2e-9330-585e290ca3a0
workflows:
  run-test:  # You can rename this workflow section if needed
    jobs:
      - run-LTAF
